### ISSUE TITLE
Wrong log message

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-vote-service#103]
I made a fresh instance without any data. When I run `docker-compose up` the vote service writes something to the log that does not look like a correct message (`foo` is the name of my instance directory):
```
foo-vote-1             | 2022/02/21 12:17:28 Receive vote count request: &{GET /internal/vote/vote_count?id=0
HTTP/1.1 1 1 map[Accept-Encoding:[gzip] User-Agent:[Go-http-client/1.1]] {} <nil> 0 [] false vote:9013 map[] map[]
<nil> map[] 172.18.0.9:40806 /internal/vote/vote_count?id=0 <nil> <nil> <nil> 0xc00033adc0}
```
Is there really a Go http client running behind or is this just a bug?

**Comment by ostcar** [comment]
This is correct. The request is from the autoupdate-service. It asks for the field `poll/vote_count`. This is a blocking request that returns as soon as there is at least one vote in one poll:

https://github.com/OpenSlides/openslides-autoupdate-service/blob/a50ae687d25ae4cfefce51f794961773bec1d1e8/pkg/datastore/source_vote_count.go#L35

**Comment by normanjaeckel** [comment]
Hm. Ok maybe you want to provide a better log content (not something like `<nil> <nil> <nil> 0xc00033adc0` which is only for debugging purposes)
