### ISSUE TITLE
Do not use the image `1.18-alpine3.13` because it's not available

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-vote-service#111]
Two remarks:

1. Please do not always update to the latest patch version
2. Please use the image version `1.18-alpine`, so it won't happen again that a version is not available anymore

**Comment by ostcar** [comment]
I updated the autoupdate-service, the icc-service and the vote-service. The first both repos already had an github action that tested the build of the dockerfile. And the vote-service was the only one that used a point-release of the base image...
