### ISSUE TITLE
Rework vote delegation handling to work with the new enable_vote_delegations setting

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-vote-service#136]
See OpenSlides/openslides-client#1512

As per OpenSlides/openslides-backend#1440 there will soon be a setting that allows administrators to enable/disable vote delegations for a meeting.

If this setting is set to true, voting and voting delegations should work as they did before.
If it is set to false, the voting service should behave as if no delegations were set at all. (i.e. proxies should not be allowed to vote for their principals, principals should be able to vote even if they have delegated their vote before).

**Comment by jsangmeister** [comment]
with https://github.com/OpenSlides/openslides-client/pull/1683 this was introduced in the client, therefor the vote service should follow suite and also respect the new setting.

**Comment by luisa-beerboom** [comment]
Hasn't this already been done with https://github.com/OpenSlides/openslides-vote-service/pull/149 ?

**Comment by ostcar** [comment]
> Hasn't this already been done with #149 ?

Yes. This issue is done
