### ISSUE TITLE
Create feature branch for template fields and replace the used template fields

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-vote-service#162]
Create a feature branch with the name `feature_remove_template_fields`. It exists with the same name in openslides-backend.
We are working on this branch to replace consecutively all template fields.
Some of the backend tests are failing, because the vote service expects the template fields and we ad to skip the tests. 
Please replace all template fields by their replacement you can see in the models.yml of the feature-branch in the backend.
Contact the backend for still not replaced template-fields in models.yml.

**Comment by ostcar** [comment]
This should be working: https://github.com/OpenSlides/openslides-vote-service/tree/feature/remove-template-fields
