### ISSUE TITLE
feature/remove_template_fields: Some errors 

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-vote-service#191]
At the moment I'm developing on https://github.com/OpenSlides/openslides-backend/pull/1672, trying to reactivate the poll-tests in backend.

Failing tests:
1. vote/test_start.py VotePollNamedYNA:test_start_poll: Error from vote-service: {'error': 'not-allowed', 'message': 'User 1 is not allowed to vote. He is not in an entitled group'}. User is definitely in the entitled group, see assert in line 105  before calling vote-service.

**Comment by ostcar** [comment]
@r-peschke were you able to solve this? Can this be closed?

**Comment by ostcar** [comment]
Since the branch was merged, I guess, this can be closed. If it still exists, then please reopen.
