### ISSUE TITLE
Unification + expansion of the environment variables

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-vote-service#209]
Please make the following changes to the environment variables:
- remove:
```
  VOTE_REDIS_HOST
  VOTE_REDIS_PORT
  VOTE_DATABASE_HOST
  VOTE_DATABASE_NAME
  VOTE_DATABASE_PASSWORD_FILE
  VOTE_DATABASE_PORT
  VOTE_DATABASE_USER
```
- add:
```
  CACHE_HOST (?)
  CACHE_PORT (?)
  DATABASE_HOST
  DATABASE_NAME
  DATABASE_PASSWORD_FILE
  DATABASE_PORT
  DATABASE_USER
```

The env vars for the DB connection should be renamed.

The `VOTE_REDIS_HOST` and `VOTE_REDIS_PORT` variables should be renamed to
`CACHE_HOST` and `CACHE_PORT` (or `MESSAGE_BUS_*` if more appropriate depending
on how redis is used in vote). If it's ever not the default value it should be
overriden in the service specific environment.

More details on these changes are in manage-service issue https://github.com/OpenSlides/openslides-manage-service/issues/224.
Also please provide non-service-specific feedback on these related issues in the
manage-service issue.

**Comment by peb-adr** [comment]
@ostcar have you forgotten about this issue?
I guess the changes would go pretty analogous to those in the AU


> The `VOTE_REDIS_HOST` and `VOTE_REDIS_PORT` variables should be renamed to `CACHE_HOST` and `CACHE_PORT` (or `MESSAGE_BUS_*` if more appropriate depending on how redis is used in vote). If it's ever not the default value it should be overriden in the service specific environment.

Also please don't forget about this rename.

**Comment by ostcar** [comment]
@peb-adr I need an answer here: https://github.com/OpenSlides/openslides-autoupdate-service/pull/715

I first have to merge the change in the autoupdate service. If you say, I can merge the change there, then I will create the changes in the other services immediately
