### ISSUE TITLE
Prevent a user from voting if he delegated his vote

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-vote-service#225]
see https://github.com/OpenSlides/openslides-vote-service/issues/221: The current behaviour of the client is to forbid a user from voting if he delegated his vote. The vote service should mimic this behaviour.

**Comment by emanuelschuetze** [comment]
my note with @ostcar:

neue Config "strict/multi mode" für Stimmrechtsübertragung
a) strict (default): Volllmachtgeber darf NICHT für sich selbst abstimmen UND nicht mehr als an eine Person übertragen.
b) multi: Volllmachtgeber darf für sich selbst abstimmen UND an mehr als eine Person übertragen.

**Comment by jsangmeister** [comment]
This is already an own issue: https://github.com/OpenSlides/openslides-backend/issues/1883

**Comment by jsangmeister** [comment]
Waiting for https://github.com/OpenSlides/openslides-backend/issues/2370. After that is done, the vote service should evaluate the new setting and act accordingly.

**Comment by jsangmeister** [comment]
> Waiting for [OpenSlides/openslides-backend#2370](https://github.com/OpenSlides/openslides-backend/issues/2370). After that is done, the vote service should evaluate the new setting and act accordingly.

Done. The new setting is called `users_forbid_delegator_to_vote`
