### ISSUE TITLE
Implement "Have I voted" url

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-vote-service#57]
The client needs to know if he has already voted or not on a specific poll. For this, we worked out a concept:

On the initial page load, the client sends out a request to the vote service requesting all "have i voted" infos for all polls on which he can vote and which are not yet in the local storage. After this, for an already-requested poll, the client will never issue a new request to the vote service: On reload, the information persists in the local storage, and if he votes, he can directly update the local value without a request to the vote service. If a new poll comes in via autoupdate, he cannot have voted yet, so he can just put `false` in the local storage. The only time a request is necessary is if the user loads the page and during his absence, a new poll was created (or he changed devices or something similar).

The route should therefore accept a list of poll ids and return for all of them whether the request user has already voted or not. This has a relatively low priority, since it is just a visual thing - worst case is the user tries to vote again and gets an error message.

**Comment by jsangmeister** [comment]
(split-up from https://github.com/OpenSlides/openslides-vote-service/issues/16)

**Comment by ostcar** [comment]
I can do this.

There could be a problem. If a user has opened two browsers and votes in one of them, then the second brower gets not informed about this. So the second brower will still show, that the user has not voted yet. When the user reloads the page, then the client will load the information, that the user has not voted from the local storage without sending a request to the vote-service. Therefore even a reload will not "fix" this.

I think this is not a big problem, since it is just a visual thing. And the situation, that a user uses two browsers should not be frequently. So we could ignore this case. But it could be strange for a user, that a reload does not solve this visual problem.

If you want to fix this, you could add a "reload" button on each started poll. If the user clicks this, a request is send to the server to check the "have I voted" state and updates the local storage.

**Comment by jsangmeister** [comment]
> There could be a problem. If a user has opened two browsers and votes in one of them, then the second brower gets not informed about this. So the second brower will still show, that the user has not voted yet. When the user reloads the page, then the client will load the information, that the user has not voted from the local storage without sending a request to the vote-service. Therefore even a reload will not "fix" this.

When the user votes, he writes manually in the local storage that he has voted. So after he reload in the second tab, the client will read the correct value from the local storage and display the poll correctly. 

We could even go so far as to implement this into the change detection of angular, so that you don't even need to reload your second tab, but this might be too much work and to resource intensive. For now, the option with reload should be enough.

**Comment by ostcar** [comment]
I don't talk about a second tab but about a second browser (or a private tab of the same browser) or the normal browser and the Electron-OpenSlides-Setup.

Currently this should not happen so often. But if we create a "vote-app" in the future, this would be a regular problem. We had the idea of the "vote-app" to prevent [this kind of attack in a future version of the vote-service](https://github.com/OpenSlides/OpenSlides/wiki/DE%3AKonzept-Geteilter-Vote-Service#manipulierte-client-software).

But of cause, we can ignore this kind of problem for now and tell users not to use two browsers and find a better solution, if we create a vote-app in the future.

**Comment by jsangmeister** [comment]
Ah ok, yes, then you are correct. But I think this (at least for now) edge case can be ignored, especially since it's a purely visual feature. Since it is not noticeable for the second browser if the first browser votes, the other tow alternatives would be polling (which would be highly imperformant) or a websocket connection between the client and the vote service which sends information to all logged in clients of one user if he votes. This would also be a good solution, but probably more work to do. But I'm open to discuss this.

**Comment by jsangmeister** [comment]
> For completeness of our discussion: Another solution would be the "reload" button.

Yes, but we also have the voting banner which is displayed at the top of the page which uses the information whether the user has voted or not. We'd also have to add the reload button there, which is where it gets ugly I think. Also, I see the reload button more as an enhancement of the initial solution.

> If we want to get automatic updates, we should not use polling or websocket but an open http connection as we already use them in the autoupdate-service and the icc-service.

Yes, this was more of a wording mistake by me - we should use our existing methods if possible.

**Comment by ostcar** [comment]
I added this feature in #58. Is this fine for you?

**Comment by ostcar** [comment]
See answer in #58
