### ISSUE TITLE
Read postgres password from secret

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-vote-service#60]
@ostcar Can you please enable reading the db password from a file given as secret? See datastore settings here.

_Originally posted by @normanjaeckel in https://github.com/OpenSlides/openslides-manage-service/pull/104#discussion_r748764035_

**Comment by ostcar** [comment]
@normanjaeckel the datastore has two settings:

```
DATASTORE_DATABASE_PASSWORD: openslides
DATASTORE_DATABASE_PASSWORD_FILE: /run/secrets/datastore_postgres_password
```

What does the first one do?

Is the password the hole content of the file or do I have to parse it in some way?

**Comment by peb-adr** [comment]
> @normanjaeckel the datastore has two settings:
> 
> ```
> DATASTORE_DATABASE_PASSWORD: openslides
> DATASTORE_DATABASE_PASSWORD_FILE: /run/secrets/datastore_postgres_password
> ```
> 
> What does the first one do?
> 
> Is the password the hole content of the file or do I have to parse it in some way?

the password will be the whole content of the file (or at least thats how its done for the  datastore and media database_password files).

To my understanding the first one is for having the possibility to directly provide the password. It should be used when the `_FILE` variant is not set. If both are set I think the `_FILE` variant should overwrite the explicit one, being the more secure alternative.

See also: https://github.com/OpenSlides/openslides-datastore-service/pull/156

**Comment by normanjaeckel** [comment]
In my opinion the variant with clear text password should be disabled. I would like to remove it from the manage service at all.

**Comment by normanjaeckel** [comment]
Waiting for this so I can merge https://github.com/OpenSlides/openslides-manage-service/pull/114
Please use `VOTE_DATABASE_USER_FILE` and `VOTE_DATABASE_PASSWORD_FILE` in prod mode and hard coded values `openslides` in dev mode.
