### ISSUE TITLE
Make schema/namespace configurable

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-vote-service#61]
The vote service is going to require the tables `poll` and `objects`, cf. [schema.sql](https://github.com/OpenSlides/openslides-vote-service/blob/ee7fef97bdc1ba3f25592b4e0106c63c2e4338bc/internal/backends/postgres/schema.sql).  Especially `objects` strikes me as a name that could potentially clash with other services in the future if they all tried to create their tables in the same namespace.

I would like to propose to either a) add a schema configuration option, e.g., to reconfigure `public.objects` to `vote.objects`, or b) rename the tables to hopefully unique names such as `vote_objects`.  Personally, I consider the former method to be cleaner and safer.

The media service's table name is also configurable, by the way, so its table can be stored as, e.g., `media.mediafile_data`.

**Comment by ostcar** [comment]
I can create a vote schema.

When I created the service, I thought it would use its own database. In this case, there would not be any name collision.

But you are correct. A Schema would be better.

Does the schema has to be configurable or is a fixed schema like "vote" or "vote_service" also ok? The library that I am using does not support variable schemas. So I either have to trust that the given schema is valid or add extra logic to prevent SQL injections in the schema name.

**Comment by gsiv** [comment]
A reasonable hard-coded name such as `vote` would be fine by me.

I was merely suggesting configurability in case the `public` schema was supposed to remain the default.
