### ISSUE TITLE
Error when using with pgbouncer (pool_mode=transaction)

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-vote-service#64]
When the `VOTE_DATABASE_HOST` is not a plane postgres server but a pgbouncer instead (which is used for connection pooling), then starting a vote will cause the following error to be logged:

    Error: starting poll in the backend: insert poll: ERROR: prepared statement "lrupsc_1_1" does not exist (SQLSTATE 26000)`

According to [this article](https://blog.bullgare.com/2019/06/pgbouncer-and-prepared-statements/) this can be fixed by using a DSN like this:

    postgres://user:pass@host:post/db_name?sslmode=disable&binary_parameters=yes

I gave this a try by adjusting https://github.com/ostcar/openslides-vote-service/blob/b0a9acaff79c76e7defcd5cec8b9e9ba4b7de48a/internal/vote/run.go#L300 , however it only led to this error:

    Waiting for postgres: failed to connect to `host=HOST user=USER database=NAME`: server error (ERROR: unsupported startup parameter: binary_parameters (SQLSTATE 08P01))

I'm not sure if the postgres library you're using doesn't support this option but if we could find a solution to this , that would be great.
Btw changing the `pool_mode=session` on our test server, resolves the issue, but that's not an option for production deployment.

**Comment by ostcar** [comment]
The Connection happens here

https://github.com/ostcar/openslides-vote-service/blob/main/internal/backends/postgres/postgres.go#L31-L47

I am using the pgx library that is also mentioned in the article you found.

But I am using a connection pool in the vote service. Maybe that is the problem? Should pgbouncer be used, when the application already uses a pool? Is it needed? If not, should I remove the pool or should you not use pgbouncer?

**Comment by peb-adr** [comment]
The pgbouncer has been itegrated into the setup for a long time now and brings a good performance/stability boost for the whole OS stack, so as I said removing it is not an option for us.
However, you using a pool on top of that may very well be the root of the problem.
Is there an easy patch i could apply to test it without your pooling or could you perhaps push a version without to branch i your repo that I can build and test?

If that fixes the problem, I propose you make your local pooling optionally disable-able by setting an env var.
Or I reverse ask, is your pooling needed?

**Comment by ostcar** [comment]
Could you test #66
