### ISSUE TITLE
Add Racecondition tests

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-vote-service#7]
Both backend must be tested to handle "parallel" votes correctly: By parallel I mean two vote requests that both first read data and one is faster in writing them. It must be ensured, that the second request behaves as intended (e.g. normal execution, or maybe an error due to the same user, ...).

Must be done for postgres and redis backend.

See https://github.com/OpenSlides/openslides-vote-service/pull/1#issuecomment-829222307

**Comment by r-peschke** [comment]
I agree with @jsangmeister and I think racecondition tests for these kind of service should be obligatory.

**Comment by ostcar** [comment]
I had a talk with Sascha and we came to the conclusion, that the current tests are good for this case and that adding test hooks in the code would not help here.
