### ISSUE TITLE
How to get "have I voted" for my vote delegations

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-vote-service#83]
The "have I voted" `curl localhost:9013/system/vote/voted?ids=1,2,3`
basically works fine for my current operator.
I currently use it as a get request and receive the information about my own current voting status.

It's currently not documented how I can get the same information about my current vote delegations. Is it enough to have it as a post-request and submit the user-ids of my delegations?

**Comment by ostcar** [comment]
At the moment you only get you own status.

Of course, we can add a feature like this.

The vote service knowns the delegations of a user. So the status for all delegations could automatically be added to the response. We don't have to change the request.

**Comment by ostcar** [comment]
@tsiegleauq we forgot to talk about this. Is this really needed? @emanuelschuetze was not sure.

**Comment by tsiegleauq** [comment]
Is there any alternative to that? We certainly need to know that one has
voted for their vote delegates. Otherwise we would be greeted with the
voting interface all the time and know that we had voted already after
trying to submit a vote.

Oskar Hahn ***@***.***> schrieb am So., 9. Jan. 2022, 11:47:

**Comment by ostcar** [comment]
I would propose, that we change the API of the response.

The request can be the same. The vote service will automatically find out all vote delegations and send a response that contains the answer for the request userID (if he can vote) and all delegations userIDs.

Example

```
{
"1":[1,2,3],
"2":[2]
}
```

The outer Ids are the requested poll IDs in the IDs in the list are user IDs that have voted. Without vote delegations, there will only be the request userID in the list.

Is this ok? Would it be easier for the client is the outer id is the user id and the inner IDs a list of pollIDs?

**Comment by ostcar** [comment]
@luisa-beerboom Is this still a thing that has to be fixed?

**Comment by luisa-beerboom** [comment]
@ostcar In short: Yes. 

Long explanation:
The client currently tracks whether the user has voted on a delegation by setting a certain value to true when the vote is sent.
This means that the client currently has no real way of knowing whether a delegation has already been voted on EXCEPT if the operator himself did it *in that very session*.

I.e. if you vote for a delegation, the component will show that you've already voted for that delegation. If you then simply reload the page, you will again be able to see the voting interface as if the vote didn't happen. You can then click on a vote option and send another vote request (and receive an error stating that you can't vote twice).

This can't be fixed unless we can get the `hasVoted` information for delegations from the voting service.

**Comment by ostcar** [comment]
@luisa-beerboom See the PR #147  Can you create a PR for the client so we can merge this together?

**Comment by luisa-beerboom** [comment]
@ostcar I'll get to it as soon as I can

**Comment by emanuelschuetze** [comment]
I think, this is done.
