### ISSUE TITLE
DEBUG logging enabled even if `OPENSLIDES_DEVELOPMENT` is set to `false`

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-vote-service#89]
The voting service enables its DEBUG logging even if `OPENSLIDES_DEVELOPMENT` is set to `false`.                                                                                                                                             

The management service sets `OPENSLIDES_DEVELOPMENT` to `false` by default which is obviously intended to disable development features, cf. 
https://github.com/OpenSlides/openslides-manage-service/blob/d7bc31f235aaa9ff2ed47315ae7851e9763314ab/pkg/config/default-config.yml#L83

Without having verified it, the problem appears to be the string comparison here, which does not account for `false`:
https://github.com/OpenSlides/openslides-vote-service/blob/c8b9a4d2c38db345c464c1280aa547dfd67bbc24/cmd/vote/main.go#L19

**Comment by jsangmeister** [comment]
I would argue that a positive string matching is more appropriate here anyway, meaning the debug mode is only enabled for specific values and not just disabled for specific values. This is how it's done in the datastore:
https://github.com/OpenSlides/openslides-datastore-service/blob/844d7b110433a5a28d10662e095a7c6a7795fb80/scripts/system/export-database-variables.sh#L9

We should unifyy this behaviour and use a standardized list of positives for all services.

**Comment by gsiv** [comment]
> We should unifyy this behaviour and use a standardized list of positives for all services.

Yes, please!

What's more, the backend, for example, enforces non-empty values for `OPENSLIDES_DEVELOPMENT`.  Setting it to `""`, as the voting service requires, yields: `ValueError: Value must be one off ('1', 'on', 'true', '0', 'off', 'false').`

That means that it is currently impossible to disable the voting service's DEBUG logging, even with custom settings, which makes the bug much more severe.  Please address this soon.
