### ISSUE TITLE
Selection of a strong cipher suite

### ISSUE THREAD

**Issue by elanfer** [OpenSlides/openslides-vote-service#95]
I read through the [BSI TR-02102-1](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102.html), which is the recommendation for cryptography methods for several use cases, e.g., asymmetric crypto. There are numerous other standards available, as I found out during my research. Examples are ISO/IEC 18033-2 or the [NIST cryptographic guidelines](https://csrc.nist.gov/Projects/cryptographic-standards-and-guidelines). However, in my opinion we should focus on the BSI recommendations and standards, which are, 1) quite similar to the others I just mentioned, and 2) because most OpenSlides users care about BSI certifications when it comes to electronic voting. 

In the following, I will discuss the different parts of a cipher suite, that are needed to perform asymmetric crypto and provide recommendations as a conclusion from the TR-02102-1. 

### Symmetric block ciphers
The BSI recommends the usage of AES-128, AES-192, AES-256. Using one of the following modes: CCM, GCM, CBC, or CTR. Since there are attacks known against GMAC, which also affect GCM, I would recommend leaving this mode out. Moreover, we should make use of the highest block size, which is AES-256. When looking at the amounts of data, that we want to encrypt, the block size will not result in a performance issue. 

Concluding this, we should use **AES-256 in CCM, CBC, or CTR mode** (with a tag length > 64 Bit for CCM, more is always better here)

### MAC (Message Authentication Code)
The recommendation here is CMAC, HMAC, or GMAC (with key len > 128, tag len > 96). Again GMAC, even if the attacks on GMAC do not have high probability for success, we should better sort it out. My recommendation would be to **use HMAC**, since it used widely  in many secure connection protocols (e.g., SSH with modern ciphers).

### Hash function
See table 4.1 in the TR, it recommends these hash functions: 
##### SHA2
SHA-256, SHA-512/256, SHA-384 and SHA-512
##### SHA3
SHA3-256, SHA3-384, SHA3-512

Since SHA3 is resistant against length attacks, I would recommend the use of SHA3. Length dependent on the library, in best case 512, more is better. ;)

### Asymmetric cipher
In the section (3) of asymmetric ciphers, the recommendation is to use either  ECIES , DLIES , or RSA. For DH problem based chiffres (DLIES and RSA), the guide recommends to use keys at a minimum length of 3000 bits, starting from 2023. Earlier than 2023, they state that 2000 bits should be sufficient. So if we decide for one of these, we should directly use the higher length or even 4096 bits. Since we should use hybrid ciphers, due to performance reasons during the voting procedure, we are talking about RSA-AES in the following, to compare it with ECIES. I'm only going to talk about these two, because I haven't found many DLIES implementations, compared to RSA-AES and ECIES, from that I would state it is not that wide distributed compared to the other two, and following from that maybe not that bullet proof (especially when it comes to implementation issues). In the following, I searched for some scientific publications, that compared ECIES with RSA-AES, and I found the publication of Martínez et al. from 2015 ([ResearchGate link](https://www.researchgate.net/publication/277941706_Security_and_Practical_Considerations_When_Implementing_the_Elliptic_Curve_Integrated_Encryption_Scheme), also published peer reviewed in Cryptologia Volume 39, 2015 - Issue 3). In their paper in section 8.3, we can find a comparison between these two methods. The authors concluded, that RSA-AES achieves better performance in low and medium security levels, but when it comes to higher security levels, ECIES can offer shorter computing times. This advantage already starts at a security level of 128, which is comparable to RSA-AES with a key length of 3072 (so our minimum requirement). Since we also have to do these computing steps on mobile, and/or older devices that are sometimes used in assemblies, I would go for ECIES in our decision. Moreover, it will give us the option to even higher the security level later, without needing a lot of more performance to compute higher RSA key lengths (assuming that none of these methods gets broken in general). 

## Conclusion 
To conclude this in short: In my opinion we are looking for a crypto library, that supports the following parts for our cipher suite:
* ECIES with:
  * AES-256 in CCM, CBC, or CTR mode
  * HMAC
  * SHA3-512
* Go lang support (Server side)
* JavaScript support (Client side)

We do not need a library that supports both languages, it is also possible to use two different libraries, that support our cipher suite needs. If you agree on this selection of ciphers, we can start evaluating crypto libraries that fit our needs. I'm happy for your comments!

**Comment by ostcar** [comment]
Thank you very much for your research. I sounds reasonable.

We could create some benchmarks how big the performance penalty for the bigger keys is.

Could you also make some suggestions what we should use for singing? The decrypt server has to sign the poll-key and the decrypted poll-data.

I found this repo that implements ecies in `go` and `typescript`. It also has an implementation in wasm that could be helpful on the client. But the library (at least the go version) uses GCM: https://github.com/ecies/go/blob/141d6a7e49e8505efff9b27b8864c8ea0125ab4a/ecies.go#L95

I only uses SHA-256. But it would be quite easy to create a patched version that uses SHA3-512 ([only a dependency has to be changed](https://github.com/ecies/go/blob/141d6a7e49e8505efff9b27b8864c8ea0125ab4a/utils.go#L4)).

It seems, that hmac is not used. Is it really necessary to use Message Authentication in our case? (I would also like to use it, but should we rule out a library that does not use it?)

**Comment by bernhardreiter** [comment]
@elanfer thanks for the overview about the algorithms.

It looks fine to use the BSI TR-02102-1 recommendations.

On the RSA versus ECIES performance: I believe this is neglectable for our use case.
If we agree that RSA based algorithms are good enough as well, we would have a wider range of implementations to chose from.

For signatures, TR-02102-1 recommends RSA oder ECDSA (variants). I consider the Merkle signatures as not relevevant for our planned "short-term" usage of signatures.

We should think about about the implementation quality and the needed performance or other parameters.
(a precondition is a comprehensive writeup about how the cryptography will be used. )
One evaluation aspect is the maturity of the implementation, which means track record of the development community and credible usage or examination by third parties. (Example  openssh, gnupg and gnutls are there many years, used in the millions and have several decades of stable development communities. (the example are chosen for components that we probably will not use on purpose.)).

**Comment by ostcar** [comment]
@elanfer Can you explain to me, why you want to rule out GCM? Which attacks are the problem you are talking about?

GCM makes the implementation easier, since it already includes padding and authentication. So there are two less steps to do errors.

I think, GCM is not a problem in our scenario. One problem is, when the nonce is reused with the same key. But in our case, with ecics the client creates a new ephemeral key for each vote/message. So even if the nonce is not random there would be no reuse.

**Comment by elanfer** [comment]
As far as I understood, it is an issue with short tags used in GCM (esp. GMAC), the probability of injecting false information is higher than in the two other methods, at same tag length. Which means GMAC has a lower integrity protection, than the others.  However, if we chose a tag length higher than 96 bits, it should be fine. More information on this issue provides the BSI TR on page 45. A description of the attack mechanism provides [this paper](https://csrc.nist.gov/csrc/media/projects/block-cipher-techniques/documents/bcm/comments/cwc-gcm/ferguson2.pdf), written by Niels Ferguson in 2005. In the end, it is appropriate to use GCM, but in my opinion we should do better to use CCM, CBC, or CTR mode.

To @bernhardreiter point on Merkle signatures, I agree. I do not believe that we will find implementations that are proven over years and do also offer a good performance.

@ostcar and I had a call last week, and we thought that this ECIES sample implementation does not completely fill our needs. Moreover, it looks not that widely used and maintained by a bigger community. I searched a bit more on GitHub and found [kyber](https://github.com/dedis/kyber), which has many contributors and forks. A bit confusing is the last commit 2 months ago, it could be because the library is already in version 3, and maybe they are not implementing on new features at the moment. Maybe you can have a look @ostcar and asses whether this might be worth trying or not, since you have a way better understanding of Go than me.

**Comment by ostcar** [comment]
I still think, that we can use GCM. The attack is only possible, if the plaintext is longer then a certain length and the amount of times the same secret is used.

In our use case we use the secret only once. And the plaintext is in most cases only 3 bytes ("Y"). In theory a vote as an infinite size when there are an infinite options to vote from. But in practice, this should never be bigger then 1kb. In this use case it would be allowed to use a authentication tag length of 32 bit.

The go standard library uses a tag length of 128 (the biggest possible number with aes). This is more then enough, even for long messages and definitely enough in our use case.

I had a look at kyber. I only looked at there [encryption code](https://github.com/dedis/kyber/blob/master/encrypt/ecies/ecies.go). As far as I can tell, the code looks fine. The way they do it is the same as I do it in [my current code](https://github.com/ostcar/openslides-vote-service/blob/5845cea796a9f953205645a9fb6587bfcedd52a9/decrypt/crypto/crypto.go#L62-L91). They also [use GCM](https://github.com/dedis/kyber/blob/4e19b71bd4b8f3749dc5f83e9b898fb9c903df85/encrypt/ecies/ecies.go#L52).

My current view is not to use any crypto library at all but just the go standard library. My current decrypt-function has only 30 lines of code. It is mutch easier to maintain this 30 lines then an external dependency. It should also be mutch cheaper to review this 30 lines instead of a project like kyber.

**Comment by elanfer** [comment]
OK, thanks for your explanation on GCM @ostcar, I have no further concerns if we use GCM with the default tag length of 128 bits, when it is that much easier and already implemented. 

Regarding your implementation:  I think it is good if we reduce the amount of dependencies and unnecessary code, if it is easy to maintain and well-structured. I have no doubts and would prefer just using a lightweight implementation based on the standard Go crypto library. As far as I can see, your code seems to fulfil these points. Even without comments I was able to figure out, what you're doing, and it was better structured than the one I've seen in kyber.

**Comment by ostcar** [comment]
We have a implemented draft. Thank you for all your input
