### ISSUE TITLE
Unlimited errors thrown at startup

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-vote-service#96]
This is thrown
```
docker-vote-1              | DEBUG 2022/02/02 14:01:29 Receive vote count event with id 0
docker-vote-1              | DEBUG 2022/02/02 14:01:29 End vote count with error: <nil>
docker-vote-1              | 2022/02/02 14:01:29 Receive vote count request: &{GET /internal/vote/vote_count?id=0 HTTP/1.1 1 1 map[Accept-Encoding:[gzip] User-Agent:[Go-http-client/1.1]] {} <nil> 0 [] false vote:9013 map[] map[] <nil> map[] 172.28.0.9:42012 /internal/vote/vote_count?id=0 <nil> <nil> <nil> 0xc0002f6ec0}
```

**Comment by ostcar** [comment]
> Another error which is thrown in the backend poll tests (may be related, therefor not opening a new issue for now):
> 
> ```
> {"error":"internal","message":"clearing counter: getting max score: ERR syntax error"}
> ```
> 
> Both seem to have been introduced by the latest PR #94, at least I found the source of the syntax error above in the changed lines.

This have to be this lines:

https://github.com/OpenSlides/openslides-vote-service/blob/19869f7977eae81c5314aa80e0f04240f0097b52/internal/backends/redis/redis.go#L313-L316

The error says, that it would be an invalid redis command. But I am sure, that it is valid.

https://redis.io/commands/zrange

But I use a syntax that was introduced in redis 6.2.0. Can you find out which version you are using?


> This is thrown
> 
> ```
> docker-vote-1              | DEBUG 2022/02/02 14:01:29 Receive vote count event with id 0
> docker-vote-1              | DEBUG 2022/02/02 14:01:29 End vote count with error: <nil>
> docker-vote-1              | 2022/02/02 14:01:29 Receive vote count request: &{GET /internal/vote/vote_count?id=0 HTTP/1.1 1 1 map[Accept-Encoding:[gzip] User-Agent:[Go-http-client/1.1]] {} <nil> 0 [] false vote:9013 map[] map[] <nil> map[] 172.28.0.9:42012 /internal/vote/vote_count?id=0 <nil> <nil> <nil> 0xc0002f6ec0}
> ```

This is not an error but a debug log and a info log.

If this messages are thrown Unlimited times, it means, the url is called Unlimited times.

The url is called from the autoupdate-service when a key like poll/X/vote_count is requested the first time. It is strange, that this happens unlimited times.

I can not reproduce this. Can you tell me exactly what you did? Could you test it with a clean database?

**Comment by ostcar** [comment]
@GabrielInTheWorld I was able to reproduce you error. It happened on an empty database. I fixed this in the PR https://github.com/OpenSlides/openslides-vote-service/pull/97 and https://github.com/OpenSlides/openslides-autoupdate-service/pull/413 You have to use both PRs together or it will not work.

**Comment by emanuelschuetze** [comment]
works now. Thanks.
