### ISSUE TITLE
Clearing counter redis syntax error

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-vote-service#98]
Another error which is thrown in the backend poll tests: 
```
{"error":"internal","message":"clearing counter: getting max score: ERR syntax error"}
```
Both seem to have been introduced by the latest PR https://github.com/OpenSlides/openslides-vote-service/pull/94, at least I found the source of the syntax error above in the changed lines.

_Originally posted by @jsangmeister in https://github.com/OpenSlides/openslides-vote-service/issues/96#issuecomment-1028004671_

**Comment by jsangmeister** [comment]
> But I use a syntax that was introduced in redis 6.2.0. Can you find out which version you are using?

For whatever reason, the main repo and the backend dev stack use different images, namely `latest` and `alpine`, but both are running redis version 6.2.6, so this does not seem to be the issue.

**Comment by ostcar** [comment]
I changed the error message in the last commit. Could you paste the current error message again?

In the problematic pr, I copied and pasted an error message, so the same error message was thrown at two places. I fixed this in the last commit.

**Comment by ostcar** [comment]
Never mind. @reiterl already did it in #99.

The problematic line is this one: https://github.com/OpenSlides/openslides-vote-service/blob/99889af0be262be4d55ed8513ee6a34f86ca7cf7/internal/backends/redis/redis.go#L321

The redis command is:

```
ZRANGE vote_counter_changes 0 0 REV WITHSCORES
```

Could you try to send it directly to the redis instance? Or do you see any syntax error in it? Here is the documentation: https://redis.io/commands/zrange

**Comment by jsangmeister** [comment]
> Never mind. @reiterl already did it in #99.

Ah, my bad, I missed that that was a different error message.

> Could you try to send it directly to the redis instance? Or do you see any syntax error in it? Here is the documentation: https://redis.io/commands/zrange

Executing it in `redis-cli` gives an empty array as response and I also did not find any other errors with the command. The only thing that came up when googling it was this one:

> redis.Do( .... does not accept an empty arguments for ZRANGE or ZREVRANGE

(in https://groups.google.com/g/golang-nuts/c/agN7e3EsriY)

Maybe you can't give `0` as arguments? Otherwise I'm out of ideas.

**Comment by ostcar** [comment]
The strange thing is, that I don't get the syntax error. If the `0` as argument was invalid, then I would expect this test to fail:

https://github.com/OpenSlides/openslides-vote-service/blob/99889af0be262be4d55ed8513ee6a34f86ca7cf7/internal/backends/redis/redis_test.go#L77-L79

The discussion you found had another problem. He uses a variable `redisparam`. If `returnnums` is false, then is varialbe is an empty string. So he is calling `.Do("ZRANGE", "entities", "0", "-1", "")`.

Can you tell me step by step what I have to do to reproduce this in the backend repo? Please assume, that I have no knowledge at all about the backend. Don't just say what I have to do, but paste the command that I have to type.

**Comment by jsangmeister** [comment]
We found out that @reiterl's local image was too old (version 6.0.7), which is why the tests were failing. Thank you for you help!
